name: Build And Push
on:
  push:
    tags:        
      - '*' 
env:
  # 设置 registry 地址
  REGISTRY: ghcr.io
  # github.repository 格式为 owner/repository
  REPO_NAME: ${{ github.repository }}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Environment Variable
        id: vars
        run: echo "::set-output name=build_version::$(git describe --tags)"
      - name: Extract metadata (tags, labels) for bark server
        id: meta-docker
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/bark-server
          tags: |
            type=sha
            type=raw,value=latest
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deploy/Dockerfile
          platforms:  |
            linux/arm
            linux/arm64
            linux/amd64
          tags: ${{ steps.meta-docker.outputs.tags }}
          labels: ${{ steps.meta-docker.outputs.labels }}
          push: true
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
